// <auto-generated />
namespace Microsoft.AspNet.Mvc.Localization
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Resources
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Microsoft.AspNet.Mvc.Localization.Resources", typeof(Resources).GetTypeInfo().Assembly);

        /// <summary>
        /// The resource string is format is invalid.
        /// </summary>
        internal static string InvalidResourceString
        {
            get { return GetString("InvalidResourceString"); }
        }

        /// <summary>
        /// The resource string is format is invalid.
        /// </summary>
        internal static string FormatInvalidResourceString()
        {
            return GetString("InvalidResourceString");
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
